# Generated by Django 5.1.4 on 2024-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product/"
            ),
        ),
    ]
