# Generated by Django 4.2.14 on 2024-08-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_alter_shippingaddress_shipping_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_pay',
            new_name='amount_paid',
        ),
    ]
